version: '3'

services:
  app-server:
    image: app:chatgpt # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: app
    ports:
      - 9090:9090
    environment:
      # 二选一
      OPENAI_API_KEY: 
      # 二选一
      OPENAI_ACCESS_TOKEN: 
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: 
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL: 
      # 反向代理，可选
      API_REVERSE_PROXY: https://gpt.pawan.krd/backend-api/conversation
      # 访问权限密钥，可选
      AUTH_SECRET_KEY: 
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST: 
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT: 
    restart: always
    links:
      - mysql-server
  nginx-server:
    build: nginx
    image: nginx:chatgpt
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/html/:/etc/nginx/html/
    restart: always
    links:
      - app-server
  mysql-server:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - /pcm/software/mysql/chatgpt/log:/var/log/mysql
      - /pcm/software/mysql/chatgpt/data/:/var/lib/mysql
      - /pcm/software/mysql/chatgpt/sql/:/home/mysql/sql
    restart: always
